// Code generated by go-asmgen (pack_s390x_gen.go). DO NOT EDIT.

//go:build s390x

package bitpack

func packBits1_VX(dst []byte, src []uint32, blocks int)
func unpackBits1_VX(dst []uint32, src []byte, blocks int)
func packBits2_VX(dst []byte, src []uint32, blocks int)
func unpackBits2_VX(dst []uint32, src []byte, blocks int)
func packBits3_VX(dst []byte, src []uint32, blocks int)
func unpackBits3_VX(dst []uint32, src []byte, blocks int)
func packBits4_VX(dst []byte, src []uint32, blocks int)
func unpackBits4_VX(dst []uint32, src []byte, blocks int)
func packBits5_VX(dst []byte, src []uint32, blocks int)
func unpackBits5_VX(dst []uint32, src []byte, blocks int)
func packBits6_VX(dst []byte, src []uint32, blocks int)
func unpackBits6_VX(dst []uint32, src []byte, blocks int)
func packBits7_VX(dst []byte, src []uint32, blocks int)
func unpackBits7_VX(dst []uint32, src []byte, blocks int)
func packBits8_VX(dst []byte, src []uint32, blocks int)
func unpackBits8_VX(dst []uint32, src []byte, blocks int)
func packBits9_VX(dst []byte, src []uint32, blocks int)
func unpackBits9_VX(dst []uint32, src []byte, blocks int)
func packBits10_VX(dst []byte, src []uint32, blocks int)
func unpackBits10_VX(dst []uint32, src []byte, blocks int)
func packBits11_VX(dst []byte, src []uint32, blocks int)
func unpackBits11_VX(dst []uint32, src []byte, blocks int)
func packBits12_VX(dst []byte, src []uint32, blocks int)
func unpackBits12_VX(dst []uint32, src []byte, blocks int)
func packBits13_VX(dst []byte, src []uint32, blocks int)
func unpackBits13_VX(dst []uint32, src []byte, blocks int)
func packBits14_VX(dst []byte, src []uint32, blocks int)
func unpackBits14_VX(dst []uint32, src []byte, blocks int)
func packBits15_VX(dst []byte, src []uint32, blocks int)
func unpackBits15_VX(dst []uint32, src []byte, blocks int)
func packBits16_VX(dst []byte, src []uint32, blocks int)
func unpackBits16_VX(dst []uint32, src []byte, blocks int)
func packBits17_VX(dst []byte, src []uint32, blocks int)
func unpackBits17_VX(dst []uint32, src []byte, blocks int)
func packBits18_VX(dst []byte, src []uint32, blocks int)
func unpackBits18_VX(dst []uint32, src []byte, blocks int)
func packBits19_VX(dst []byte, src []uint32, blocks int)
func unpackBits19_VX(dst []uint32, src []byte, blocks int)
func packBits20_VX(dst []byte, src []uint32, blocks int)
func unpackBits20_VX(dst []uint32, src []byte, blocks int)
func packBits21_VX(dst []byte, src []uint32, blocks int)
func unpackBits21_VX(dst []uint32, src []byte, blocks int)
func packBits22_VX(dst []byte, src []uint32, blocks int)
func unpackBits22_VX(dst []uint32, src []byte, blocks int)
func packBits23_VX(dst []byte, src []uint32, blocks int)
func unpackBits23_VX(dst []uint32, src []byte, blocks int)
func packBits24_VX(dst []byte, src []uint32, blocks int)
func unpackBits24_VX(dst []uint32, src []byte, blocks int)
func packBits25_VX(dst []byte, src []uint32, blocks int)
func unpackBits25_VX(dst []uint32, src []byte, blocks int)
func packBits26_VX(dst []byte, src []uint32, blocks int)
func unpackBits26_VX(dst []uint32, src []byte, blocks int)
func packBits27_VX(dst []byte, src []uint32, blocks int)
func unpackBits27_VX(dst []uint32, src []byte, blocks int)
func packBits28_VX(dst []byte, src []uint32, blocks int)
func unpackBits28_VX(dst []uint32, src []byte, blocks int)
func packBits29_VX(dst []byte, src []uint32, blocks int)
func unpackBits29_VX(dst []uint32, src []byte, blocks int)
func packBits30_VX(dst []byte, src []uint32, blocks int)
func unpackBits30_VX(dst []uint32, src []byte, blocks int)
func packBits31_VX(dst []byte, src []uint32, blocks int)
func unpackBits31_VX(dst []uint32, src []byte, blocks int)
func packBits32_VX(dst []byte, src []uint32, blocks int)
func unpackBits32_VX(dst []uint32, src []byte, blocks int)

var packVXtab = [33]func(dst []byte, src []uint32, blocks int){
	1: packBits1_VX,
	2: packBits2_VX,
	3: packBits3_VX,
	4: packBits4_VX,
	5: packBits5_VX,
	6: packBits6_VX,
	7: packBits7_VX,
	8: packBits8_VX,
	9: packBits9_VX,
	10: packBits10_VX,
	11: packBits11_VX,
	12: packBits12_VX,
	13: packBits13_VX,
	14: packBits14_VX,
	15: packBits15_VX,
	16: packBits16_VX,
	17: packBits17_VX,
	18: packBits18_VX,
	19: packBits19_VX,
	20: packBits20_VX,
	21: packBits21_VX,
	22: packBits22_VX,
	23: packBits23_VX,
	24: packBits24_VX,
	25: packBits25_VX,
	26: packBits26_VX,
	27: packBits27_VX,
	28: packBits28_VX,
	29: packBits29_VX,
	30: packBits30_VX,
	31: packBits31_VX,
	32: packBits32_VX,
}

var unpackVXtab = [33]func(dst []uint32, src []byte, blocks int){
	1: unpackBits1_VX,
	2: unpackBits2_VX,
	3: unpackBits3_VX,
	4: unpackBits4_VX,
	5: unpackBits5_VX,
	6: unpackBits6_VX,
	7: unpackBits7_VX,
	8: unpackBits8_VX,
	9: unpackBits9_VX,
	10: unpackBits10_VX,
	11: unpackBits11_VX,
	12: unpackBits12_VX,
	13: unpackBits13_VX,
	14: unpackBits14_VX,
	15: unpackBits15_VX,
	16: unpackBits16_VX,
	17: unpackBits17_VX,
	18: unpackBits18_VX,
	19: unpackBits19_VX,
	20: unpackBits20_VX,
	21: unpackBits21_VX,
	22: unpackBits22_VX,
	23: unpackBits23_VX,
	24: unpackBits24_VX,
	25: unpackBits25_VX,
	26: unpackBits26_VX,
	27: unpackBits27_VX,
	28: unpackBits28_VX,
	29: unpackBits29_VX,
	30: unpackBits30_VX,
	31: unpackBits31_VX,
	32: unpackBits32_VX,
}
