// Code generated by go-asmgen (pack_ppc64le_gen.go). DO NOT EDIT.

//go:build ppc64le

package bitpack

func packBits1_VSX(dst []byte, src []uint32, blocks int)
func unpackBits1_VSX(dst []uint32, src []byte, blocks int)
func packBits2_VSX(dst []byte, src []uint32, blocks int)
func unpackBits2_VSX(dst []uint32, src []byte, blocks int)
func packBits3_VSX(dst []byte, src []uint32, blocks int)
func unpackBits3_VSX(dst []uint32, src []byte, blocks int)
func packBits4_VSX(dst []byte, src []uint32, blocks int)
func unpackBits4_VSX(dst []uint32, src []byte, blocks int)
func packBits5_VSX(dst []byte, src []uint32, blocks int)
func unpackBits5_VSX(dst []uint32, src []byte, blocks int)
func packBits6_VSX(dst []byte, src []uint32, blocks int)
func unpackBits6_VSX(dst []uint32, src []byte, blocks int)
func packBits7_VSX(dst []byte, src []uint32, blocks int)
func unpackBits7_VSX(dst []uint32, src []byte, blocks int)
func packBits8_VSX(dst []byte, src []uint32, blocks int)
func unpackBits8_VSX(dst []uint32, src []byte, blocks int)
func packBits9_VSX(dst []byte, src []uint32, blocks int)
func unpackBits9_VSX(dst []uint32, src []byte, blocks int)
func packBits10_VSX(dst []byte, src []uint32, blocks int)
func unpackBits10_VSX(dst []uint32, src []byte, blocks int)
func packBits11_VSX(dst []byte, src []uint32, blocks int)
func unpackBits11_VSX(dst []uint32, src []byte, blocks int)
func packBits12_VSX(dst []byte, src []uint32, blocks int)
func unpackBits12_VSX(dst []uint32, src []byte, blocks int)
func packBits13_VSX(dst []byte, src []uint32, blocks int)
func unpackBits13_VSX(dst []uint32, src []byte, blocks int)
func packBits14_VSX(dst []byte, src []uint32, blocks int)
func unpackBits14_VSX(dst []uint32, src []byte, blocks int)
func packBits15_VSX(dst []byte, src []uint32, blocks int)
func unpackBits15_VSX(dst []uint32, src []byte, blocks int)
func packBits16_VSX(dst []byte, src []uint32, blocks int)
func unpackBits16_VSX(dst []uint32, src []byte, blocks int)
func packBits17_VSX(dst []byte, src []uint32, blocks int)
func unpackBits17_VSX(dst []uint32, src []byte, blocks int)
func packBits18_VSX(dst []byte, src []uint32, blocks int)
func unpackBits18_VSX(dst []uint32, src []byte, blocks int)
func packBits19_VSX(dst []byte, src []uint32, blocks int)
func unpackBits19_VSX(dst []uint32, src []byte, blocks int)
func packBits20_VSX(dst []byte, src []uint32, blocks int)
func unpackBits20_VSX(dst []uint32, src []byte, blocks int)
func packBits21_VSX(dst []byte, src []uint32, blocks int)
func unpackBits21_VSX(dst []uint32, src []byte, blocks int)
func packBits22_VSX(dst []byte, src []uint32, blocks int)
func unpackBits22_VSX(dst []uint32, src []byte, blocks int)
func packBits23_VSX(dst []byte, src []uint32, blocks int)
func unpackBits23_VSX(dst []uint32, src []byte, blocks int)
func packBits24_VSX(dst []byte, src []uint32, blocks int)
func unpackBits24_VSX(dst []uint32, src []byte, blocks int)
func packBits25_VSX(dst []byte, src []uint32, blocks int)
func unpackBits25_VSX(dst []uint32, src []byte, blocks int)
func packBits26_VSX(dst []byte, src []uint32, blocks int)
func unpackBits26_VSX(dst []uint32, src []byte, blocks int)
func packBits27_VSX(dst []byte, src []uint32, blocks int)
func unpackBits27_VSX(dst []uint32, src []byte, blocks int)
func packBits28_VSX(dst []byte, src []uint32, blocks int)
func unpackBits28_VSX(dst []uint32, src []byte, blocks int)
func packBits29_VSX(dst []byte, src []uint32, blocks int)
func unpackBits29_VSX(dst []uint32, src []byte, blocks int)
func packBits30_VSX(dst []byte, src []uint32, blocks int)
func unpackBits30_VSX(dst []uint32, src []byte, blocks int)
func packBits31_VSX(dst []byte, src []uint32, blocks int)
func unpackBits31_VSX(dst []uint32, src []byte, blocks int)
func packBits32_VSX(dst []byte, src []uint32, blocks int)
func unpackBits32_VSX(dst []uint32, src []byte, blocks int)

var packVSXtab = [33]func(dst []byte, src []uint32, blocks int){
	1: packBits1_VSX,
	2: packBits2_VSX,
	3: packBits3_VSX,
	4: packBits4_VSX,
	5: packBits5_VSX,
	6: packBits6_VSX,
	7: packBits7_VSX,
	8: packBits8_VSX,
	9: packBits9_VSX,
	10: packBits10_VSX,
	11: packBits11_VSX,
	12: packBits12_VSX,
	13: packBits13_VSX,
	14: packBits14_VSX,
	15: packBits15_VSX,
	16: packBits16_VSX,
	17: packBits17_VSX,
	18: packBits18_VSX,
	19: packBits19_VSX,
	20: packBits20_VSX,
	21: packBits21_VSX,
	22: packBits22_VSX,
	23: packBits23_VSX,
	24: packBits24_VSX,
	25: packBits25_VSX,
	26: packBits26_VSX,
	27: packBits27_VSX,
	28: packBits28_VSX,
	29: packBits29_VSX,
	30: packBits30_VSX,
	31: packBits31_VSX,
	32: packBits32_VSX,
}

var unpackVSXtab = [33]func(dst []uint32, src []byte, blocks int){
	1: unpackBits1_VSX,
	2: unpackBits2_VSX,
	3: unpackBits3_VSX,
	4: unpackBits4_VSX,
	5: unpackBits5_VSX,
	6: unpackBits6_VSX,
	7: unpackBits7_VSX,
	8: unpackBits8_VSX,
	9: unpackBits9_VSX,
	10: unpackBits10_VSX,
	11: unpackBits11_VSX,
	12: unpackBits12_VSX,
	13: unpackBits13_VSX,
	14: unpackBits14_VSX,
	15: unpackBits15_VSX,
	16: unpackBits16_VSX,
	17: unpackBits17_VSX,
	18: unpackBits18_VSX,
	19: unpackBits19_VSX,
	20: unpackBits20_VSX,
	21: unpackBits21_VSX,
	22: unpackBits22_VSX,
	23: unpackBits23_VSX,
	24: unpackBits24_VSX,
	25: unpackBits25_VSX,
	26: unpackBits26_VSX,
	27: unpackBits27_VSX,
	28: unpackBits28_VSX,
	29: unpackBits29_VSX,
	30: unpackBits30_VSX,
	31: unpackBits31_VSX,
	32: unpackBits32_VSX,
}
