// Code generated by go-asmgen (pack_gen.go). DO NOT EDIT.

//go:build amd64

package bitpack

func packBits1_SSE(dst []byte, src []uint32, blocks int)
func packBits1_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits1_SSE(dst []uint32, src []byte, blocks int)
func unpackBits1_AVX2(dst []uint32, src []byte, blocks int)
func packBits2_SSE(dst []byte, src []uint32, blocks int)
func packBits2_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits2_SSE(dst []uint32, src []byte, blocks int)
func unpackBits2_AVX2(dst []uint32, src []byte, blocks int)
func packBits3_SSE(dst []byte, src []uint32, blocks int)
func packBits3_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits3_SSE(dst []uint32, src []byte, blocks int)
func unpackBits3_AVX2(dst []uint32, src []byte, blocks int)
func packBits4_SSE(dst []byte, src []uint32, blocks int)
func packBits4_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits4_SSE(dst []uint32, src []byte, blocks int)
func unpackBits4_AVX2(dst []uint32, src []byte, blocks int)
func packBits5_SSE(dst []byte, src []uint32, blocks int)
func packBits5_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits5_SSE(dst []uint32, src []byte, blocks int)
func unpackBits5_AVX2(dst []uint32, src []byte, blocks int)
func packBits6_SSE(dst []byte, src []uint32, blocks int)
func packBits6_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits6_SSE(dst []uint32, src []byte, blocks int)
func unpackBits6_AVX2(dst []uint32, src []byte, blocks int)
func packBits7_SSE(dst []byte, src []uint32, blocks int)
func packBits7_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits7_SSE(dst []uint32, src []byte, blocks int)
func unpackBits7_AVX2(dst []uint32, src []byte, blocks int)
func packBits8_SSE(dst []byte, src []uint32, blocks int)
func packBits8_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits8_SSE(dst []uint32, src []byte, blocks int)
func unpackBits8_AVX2(dst []uint32, src []byte, blocks int)
func packBits9_SSE(dst []byte, src []uint32, blocks int)
func packBits9_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits9_SSE(dst []uint32, src []byte, blocks int)
func unpackBits9_AVX2(dst []uint32, src []byte, blocks int)
func packBits10_SSE(dst []byte, src []uint32, blocks int)
func packBits10_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits10_SSE(dst []uint32, src []byte, blocks int)
func unpackBits10_AVX2(dst []uint32, src []byte, blocks int)
func packBits11_SSE(dst []byte, src []uint32, blocks int)
func packBits11_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits11_SSE(dst []uint32, src []byte, blocks int)
func unpackBits11_AVX2(dst []uint32, src []byte, blocks int)
func packBits12_SSE(dst []byte, src []uint32, blocks int)
func packBits12_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits12_SSE(dst []uint32, src []byte, blocks int)
func unpackBits12_AVX2(dst []uint32, src []byte, blocks int)
func packBits13_SSE(dst []byte, src []uint32, blocks int)
func packBits13_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits13_SSE(dst []uint32, src []byte, blocks int)
func unpackBits13_AVX2(dst []uint32, src []byte, blocks int)
func packBits14_SSE(dst []byte, src []uint32, blocks int)
func packBits14_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits14_SSE(dst []uint32, src []byte, blocks int)
func unpackBits14_AVX2(dst []uint32, src []byte, blocks int)
func packBits15_SSE(dst []byte, src []uint32, blocks int)
func packBits15_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits15_SSE(dst []uint32, src []byte, blocks int)
func unpackBits15_AVX2(dst []uint32, src []byte, blocks int)
func packBits16_SSE(dst []byte, src []uint32, blocks int)
func packBits16_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits16_SSE(dst []uint32, src []byte, blocks int)
func unpackBits16_AVX2(dst []uint32, src []byte, blocks int)
func packBits17_SSE(dst []byte, src []uint32, blocks int)
func packBits17_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits17_SSE(dst []uint32, src []byte, blocks int)
func unpackBits17_AVX2(dst []uint32, src []byte, blocks int)
func packBits18_SSE(dst []byte, src []uint32, blocks int)
func packBits18_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits18_SSE(dst []uint32, src []byte, blocks int)
func unpackBits18_AVX2(dst []uint32, src []byte, blocks int)
func packBits19_SSE(dst []byte, src []uint32, blocks int)
func packBits19_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits19_SSE(dst []uint32, src []byte, blocks int)
func unpackBits19_AVX2(dst []uint32, src []byte, blocks int)
func packBits20_SSE(dst []byte, src []uint32, blocks int)
func packBits20_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits20_SSE(dst []uint32, src []byte, blocks int)
func unpackBits20_AVX2(dst []uint32, src []byte, blocks int)
func packBits21_SSE(dst []byte, src []uint32, blocks int)
func packBits21_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits21_SSE(dst []uint32, src []byte, blocks int)
func unpackBits21_AVX2(dst []uint32, src []byte, blocks int)
func packBits22_SSE(dst []byte, src []uint32, blocks int)
func packBits22_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits22_SSE(dst []uint32, src []byte, blocks int)
func unpackBits22_AVX2(dst []uint32, src []byte, blocks int)
func packBits23_SSE(dst []byte, src []uint32, blocks int)
func packBits23_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits23_SSE(dst []uint32, src []byte, blocks int)
func unpackBits23_AVX2(dst []uint32, src []byte, blocks int)
func packBits24_SSE(dst []byte, src []uint32, blocks int)
func packBits24_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits24_SSE(dst []uint32, src []byte, blocks int)
func unpackBits24_AVX2(dst []uint32, src []byte, blocks int)
func packBits25_SSE(dst []byte, src []uint32, blocks int)
func packBits25_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits25_SSE(dst []uint32, src []byte, blocks int)
func unpackBits25_AVX2(dst []uint32, src []byte, blocks int)
func packBits26_SSE(dst []byte, src []uint32, blocks int)
func packBits26_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits26_SSE(dst []uint32, src []byte, blocks int)
func unpackBits26_AVX2(dst []uint32, src []byte, blocks int)
func packBits27_SSE(dst []byte, src []uint32, blocks int)
func packBits27_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits27_SSE(dst []uint32, src []byte, blocks int)
func unpackBits27_AVX2(dst []uint32, src []byte, blocks int)
func packBits28_SSE(dst []byte, src []uint32, blocks int)
func packBits28_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits28_SSE(dst []uint32, src []byte, blocks int)
func unpackBits28_AVX2(dst []uint32, src []byte, blocks int)
func packBits29_SSE(dst []byte, src []uint32, blocks int)
func packBits29_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits29_SSE(dst []uint32, src []byte, blocks int)
func unpackBits29_AVX2(dst []uint32, src []byte, blocks int)
func packBits30_SSE(dst []byte, src []uint32, blocks int)
func packBits30_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits30_SSE(dst []uint32, src []byte, blocks int)
func unpackBits30_AVX2(dst []uint32, src []byte, blocks int)
func packBits31_SSE(dst []byte, src []uint32, blocks int)
func packBits31_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits31_SSE(dst []uint32, src []byte, blocks int)
func unpackBits31_AVX2(dst []uint32, src []byte, blocks int)
func packBits32_SSE(dst []byte, src []uint32, blocks int)
func packBits32_AVX2(dst []byte, src []uint32, blocks int)
func unpackBits32_SSE(dst []uint32, src []byte, blocks int)
func unpackBits32_AVX2(dst []uint32, src []byte, blocks int)

var packSSEtab = [33]func(dst []byte, src []uint32, blocks int){
	1: packBits1_SSE,
	2: packBits2_SSE,
	3: packBits3_SSE,
	4: packBits4_SSE,
	5: packBits5_SSE,
	6: packBits6_SSE,
	7: packBits7_SSE,
	8: packBits8_SSE,
	9: packBits9_SSE,
	10: packBits10_SSE,
	11: packBits11_SSE,
	12: packBits12_SSE,
	13: packBits13_SSE,
	14: packBits14_SSE,
	15: packBits15_SSE,
	16: packBits16_SSE,
	17: packBits17_SSE,
	18: packBits18_SSE,
	19: packBits19_SSE,
	20: packBits20_SSE,
	21: packBits21_SSE,
	22: packBits22_SSE,
	23: packBits23_SSE,
	24: packBits24_SSE,
	25: packBits25_SSE,
	26: packBits26_SSE,
	27: packBits27_SSE,
	28: packBits28_SSE,
	29: packBits29_SSE,
	30: packBits30_SSE,
	31: packBits31_SSE,
	32: packBits32_SSE,
}

var packAVX2tab = [33]func(dst []byte, src []uint32, blocks int){
	1: packBits1_AVX2,
	2: packBits2_AVX2,
	3: packBits3_AVX2,
	4: packBits4_AVX2,
	5: packBits5_AVX2,
	6: packBits6_AVX2,
	7: packBits7_AVX2,
	8: packBits8_AVX2,
	9: packBits9_AVX2,
	10: packBits10_AVX2,
	11: packBits11_AVX2,
	12: packBits12_AVX2,
	13: packBits13_AVX2,
	14: packBits14_AVX2,
	15: packBits15_AVX2,
	16: packBits16_AVX2,
	17: packBits17_AVX2,
	18: packBits18_AVX2,
	19: packBits19_AVX2,
	20: packBits20_AVX2,
	21: packBits21_AVX2,
	22: packBits22_AVX2,
	23: packBits23_AVX2,
	24: packBits24_AVX2,
	25: packBits25_AVX2,
	26: packBits26_AVX2,
	27: packBits27_AVX2,
	28: packBits28_AVX2,
	29: packBits29_AVX2,
	30: packBits30_AVX2,
	31: packBits31_AVX2,
	32: packBits32_AVX2,
}

var unpackSSEtab = [33]func(dst []uint32, src []byte, blocks int){
	1: unpackBits1_SSE,
	2: unpackBits2_SSE,
	3: unpackBits3_SSE,
	4: unpackBits4_SSE,
	5: unpackBits5_SSE,
	6: unpackBits6_SSE,
	7: unpackBits7_SSE,
	8: unpackBits8_SSE,
	9: unpackBits9_SSE,
	10: unpackBits10_SSE,
	11: unpackBits11_SSE,
	12: unpackBits12_SSE,
	13: unpackBits13_SSE,
	14: unpackBits14_SSE,
	15: unpackBits15_SSE,
	16: unpackBits16_SSE,
	17: unpackBits17_SSE,
	18: unpackBits18_SSE,
	19: unpackBits19_SSE,
	20: unpackBits20_SSE,
	21: unpackBits21_SSE,
	22: unpackBits22_SSE,
	23: unpackBits23_SSE,
	24: unpackBits24_SSE,
	25: unpackBits25_SSE,
	26: unpackBits26_SSE,
	27: unpackBits27_SSE,
	28: unpackBits28_SSE,
	29: unpackBits29_SSE,
	30: unpackBits30_SSE,
	31: unpackBits31_SSE,
	32: unpackBits32_SSE,
}

var unpackAVX2tab = [33]func(dst []uint32, src []byte, blocks int){
	1: unpackBits1_AVX2,
	2: unpackBits2_AVX2,
	3: unpackBits3_AVX2,
	4: unpackBits4_AVX2,
	5: unpackBits5_AVX2,
	6: unpackBits6_AVX2,
	7: unpackBits7_AVX2,
	8: unpackBits8_AVX2,
	9: unpackBits9_AVX2,
	10: unpackBits10_AVX2,
	11: unpackBits11_AVX2,
	12: unpackBits12_AVX2,
	13: unpackBits13_AVX2,
	14: unpackBits14_AVX2,
	15: unpackBits15_AVX2,
	16: unpackBits16_AVX2,
	17: unpackBits17_AVX2,
	18: unpackBits18_AVX2,
	19: unpackBits19_AVX2,
	20: unpackBits20_AVX2,
	21: unpackBits21_AVX2,
	22: unpackBits22_AVX2,
	23: unpackBits23_AVX2,
	24: unpackBits24_AVX2,
	25: unpackBits25_AVX2,
	26: unpackBits26_AVX2,
	27: unpackBits27_AVX2,
	28: unpackBits28_AVX2,
	29: unpackBits29_AVX2,
	30: unpackBits30_AVX2,
	31: unpackBits31_AVX2,
	32: unpackBits32_AVX2,
}
